name: Economy
version: 1.0
main: Economy.EconomyPlugin
api-version: 1.19
authors: [ Gnaris ]
depend: [SP_Database]
commands:
  money:
    aliases: [balance, wallet]
  pay:
  economy:
    aliases: [eco]
permissions:
  sperias.wallet.command.economy:
    description: "Manage money"