name: Economy
version: 1.0
main: Economy.EconomyAPI
api-version: 1.17
authors: [ Gnaris ]
depend: [Database]
commands:
  money:
    aliases: [balance, wallet]
  pay:
  economy:
    aliases: [eco]
permissions:
  sperias.wallet.command.economy:
    description: "Manage money"