name: SP_Wallet
version: 1.0
main: SPWallet.SPWallet
api-version: 1.19
authors: [ Gnaris ]

depend: [SP_Database]
commands:
  wallet:
  spwallet:
permissions:
  sperias.wallet.command.spwallet:
    description: "Manage money"